{
  "resultsPerPage": 4,
  "startIndex": 0,
  "totalResults": 4,
  "result": {
    "CVE_data_type": "CVE",
    "CVE_data_format": "MITRE",
    "CVE_data_version": "4.0",
    "CVE_data_timestamp": "2021-05-16T14:40Z",
    "CVE_Items": [
      {
        "cve": {
          "data_type": "CVE",
          "data_format": "MITRE",
          "data_version": "4.0",
          "CVE_data_meta": {
            "ID": "CVE-2018-1000808",
            "ASSIGNER": "cve@mitre.org"
          },
          "problemtype": {
            "problemtype_data": [
              {
                "description": [
                  {
                    "lang": "en",
                    "value": "CWE-404"
                  }
                ]
              }
            ]
          },
          "references": {
            "reference_data": [
              {
                "url": "https://github.com/pyca/pyopenssl/pull/723",
                "name": "https://github.com/pyca/pyopenssl/pull/723",
                "refsource": "CONFIRM",
                "tags": [
                  "Patch",
                  "Third Party Advisory"
                ]
              },
              {
                "url": "https://usn.ubuntu.com/3813-1/",
                "name": "USN-3813-1",
                "refsource": "UBUNTU",
                "tags": [
                  "Third Party Advisory"
                ]
              },
              {
                "url": "https://access.redhat.com/errata/RHSA-2019:0085",
                "name": "RHSA-2019:0085",
                "refsource": "REDHAT",
                "tags": [
                  "Third Party Advisory"
                ]
              },
              {
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html",
                "name": "openSUSE-SU-2019:1104",
                "refsource": "SUSE",
                "tags": []
              }
            ]
          },
          "description": {
            "description_data": [
              {
                "lang": "en",
                "value": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0."
              }
            ]
          }
        },
        "configurations": {
          "CVE_data_version": "4.0",
          "nodes": [
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:pyopenssl_project:pyopenssl:*:*:*:*:*:*:*:*",
                  "versionEndExcluding": "17.5.0",
                  "cpe_name": []
                }
              ]
            },
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
                  "cpe_name": []
                }
              ]
            },
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:redhat:openstack:13.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:redhat:gluster_storage:3.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                }
              ]
            }
          ]
        },
        "impact": {
          "baseMetricV3": {
            "cvssV3": {
              "version": "3.0",
              "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "attackVector": "NETWORK",
              "attackComplexity": "HIGH",
              "privilegesRequired": "NONE",
              "userInteraction": "NONE",
              "scope": "UNCHANGED",
              "confidentialityImpact": "NONE",
              "integrityImpact": "NONE",
              "availabilityImpact": "HIGH",
              "baseScore": 5.9,
              "baseSeverity": "MEDIUM"
            },
            "exploitabilityScore": 2.2,
            "impactScore": 3.6
          },
          "baseMetricV2": {
            "cvssV2": {
              "version": "2.0",
              "vectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
              "accessVector": "NETWORK",
              "accessComplexity": "MEDIUM",
              "authentication": "NONE",
              "confidentialityImpact": "NONE",
              "integrityImpact": "NONE",
              "availabilityImpact": "PARTIAL",
              "baseScore": 4.3
            },
            "severity": "MEDIUM",
            "exploitabilityScore": 8.6,
            "impactScore": 2.9,
            "acInsufInfo": false,
            "obtainAllPrivilege": false,
            "obtainUserPrivilege": false,
            "obtainOtherPrivilege": false,
            "userInteractionRequired": false
          }
        },
        "publishedDate": "2018-10-08T15:29Z",
        "lastModifiedDate": "2020-10-15T13:28Z"
      },
      {
        "cve": {
          "data_type": "CVE",
          "data_format": "MITRE",
          "data_version": "4.0",
          "CVE_data_meta": {
            "ID": "CVE-2018-1000807",
            "ASSIGNER": "cve@mitre.org"
          },
          "problemtype": {
            "problemtype_data": [
              {
                "description": [
                  {
                    "lang": "en",
                    "value": "CWE-416"
                  }
                ]
              }
            ]
          },
          "references": {
            "reference_data": [
              {
                "url": "https://github.com/pyca/pyopenssl/pull/723",
                "name": "https://github.com/pyca/pyopenssl/pull/723",
                "refsource": "CONFIRM",
                "tags": [
                  "Patch",
                  "Third Party Advisory"
                ]
              },
              {
                "url": "https://usn.ubuntu.com/3813-1/",
                "name": "USN-3813-1",
                "refsource": "UBUNTU",
                "tags": [
                  "Third Party Advisory"
                ]
              },
              {
                "url": "https://access.redhat.com/errata/RHSA-2019:0085",
                "name": "RHSA-2019:0085",
                "refsource": "REDHAT",
                "tags": [
                  "Third Party Advisory"
                ]
              },
              {
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html",
                "name": "openSUSE-SU-2019:1104",
                "refsource": "SUSE",
                "tags": [
                  "Mailing List",
                  "Third Party Advisory"
                ]
              }
            ]
          },
          "description": {
            "description_data": [
              {
                "lang": "en",
                "value": "Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0."
              }
            ]
          }
        },
        "configurations": {
          "CVE_data_version": "4.0",
          "nodes": [
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:pyopenssl:pyopenssl:*:*:*:*:*:*:*:*",
                  "versionEndExcluding": "17.5.0",
                  "cpe_name": []
                }
              ]
            },
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
                  "cpe_name": []
                }
              ]
            },
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:redhat:openstack:13.0:*:*:*:*:*:*:*",
                  "cpe_name": []
                }
              ]
            }
          ]
        },
        "impact": {
          "baseMetricV3": {
            "cvssV3": {
              "version": "3.1",
              "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "attackVector": "NETWORK",
              "attackComplexity": "HIGH",
              "privilegesRequired": "NONE",
              "userInteraction": "NONE",
              "scope": "UNCHANGED",
              "confidentialityImpact": "HIGH",
              "integrityImpact": "HIGH",
              "availabilityImpact": "HIGH",
              "baseScore": 8.1,
              "baseSeverity": "HIGH"
            },
            "exploitabilityScore": 2.2,
            "impactScore": 5.9
          },
          "baseMetricV2": {
            "cvssV2": {
              "version": "2.0",
              "vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
              "accessVector": "NETWORK",
              "accessComplexity": "MEDIUM",
              "authentication": "NONE",
              "confidentialityImpact": "PARTIAL",
              "integrityImpact": "PARTIAL",
              "availabilityImpact": "PARTIAL",
              "baseScore": 6.8
            },
            "severity": "MEDIUM",
            "exploitabilityScore": 8.6,
            "impactScore": 6.4,
            "acInsufInfo": false,
            "obtainAllPrivilege": false,
            "obtainUserPrivilege": false,
            "obtainOtherPrivilege": false,
            "userInteractionRequired": false
          }
        },
        "publishedDate": "2018-10-08T15:29Z",
        "lastModifiedDate": "2019-09-27T12:21Z"
      },
      {
        "cve": {
          "data_type": "CVE",
          "data_format": "MITRE",
          "data_version": "4.0",
          "CVE_data_meta": {
            "ID": "CVE-2016-9015",
            "ASSIGNER": "cve@mitre.org"
          },
          "problemtype": {
            "problemtype_data": [
              {
                "description": [
                  {
                    "lang": "en",
                    "value": "CWE-295"
                  }
                ]
              }
            ]
          },
          "references": {
            "reference_data": [
              {
                "url": "http://www.securityfocus.com/bid/93941",
                "name": "93941",
                "refsource": "BID",
                "tags": [
                  "Third Party Advisory",
                  "VDB Entry"
                ]
              },
              {
                "url": "http://www.openwall.com/lists/oss-security/2016/10/27/6",
                "name": "[oss-security] 20161027 CVE-2016-9015: Python urllib3 1.17 and 1.18 certificate verification failure",
                "refsource": "MLIST",
                "tags": [
                  "Mailing List",
                  "Mitigation"
                ]
              }
            ]
          },
          "description": {
            "description_data": [
              {
                "lang": "en",
                "value": "Versions 1.17 and 1.18 of the Python urllib3 library suffer from a vulnerability that can cause them, in certain configurations, to not correctly validate TLS certificates. This places users of the library with those configurations at risk of man-in-the-middle and information leakage attacks. This vulnerability affects users using versions 1.17 and 1.18 of the urllib3 library, who are using the optional PyOpenSSL support for TLS instead of the regular standard library TLS backend, and who are using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely uncommon configuration, so the security impact of this vulnerability is low."
              }
            ]
          }
        },
        "configurations": {
          "CVE_data_version": "4.0",
          "nodes": [
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:python:urllib3:1.17:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:python:urllib3:1.18:*:*:*:*:*:*:*",
                  "cpe_name": []
                }
              ]
            }
          ]
        },
        "impact": {
          "baseMetricV3": {
            "cvssV3": {
              "version": "3.0",
              "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
              "attackVector": "NETWORK",
              "attackComplexity": "HIGH",
              "privilegesRequired": "NONE",
              "userInteraction": "NONE",
              "scope": "UNCHANGED",
              "confidentialityImpact": "LOW",
              "integrityImpact": "NONE",
              "availabilityImpact": "NONE",
              "baseScore": 3.7,
              "baseSeverity": "LOW"
            },
            "exploitabilityScore": 2.2,
            "impactScore": 1.4
          },
          "baseMetricV2": {
            "cvssV2": {
              "version": "2.0",
              "vectorString": "AV:N/AC:H/Au:N/C:P/I:N/A:N",
              "accessVector": "NETWORK",
              "accessComplexity": "HIGH",
              "authentication": "NONE",
              "confidentialityImpact": "PARTIAL",
              "integrityImpact": "NONE",
              "availabilityImpact": "NONE",
              "baseScore": 2.6
            },
            "severity": "LOW",
            "exploitabilityScore": 4.9,
            "impactScore": 2.9,
            "obtainAllPrivilege": false,
            "obtainUserPrivilege": false,
            "obtainOtherPrivilege": false,
            "userInteractionRequired": false
          }
        },
        "publishedDate": "2017-01-11T16:59Z",
        "lastModifiedDate": "2017-01-13T13:09Z"
      },
      {
        "cve": {
          "data_type": "CVE",
          "data_format": "MITRE",
          "data_version": "4.0",
          "CVE_data_meta": {
            "ID": "CVE-2013-4314",
            "ASSIGNER": "secalert@redhat.com"
          },
          "problemtype": {
            "problemtype_data": [
              {
                "description": [
                  {
                    "lang": "en",
                    "value": "CWE-20"
                  }
                ]
              }
            ]
          },
          "references": {
            "reference_data": [
              {
                "url": "http://www.openwall.com/lists/oss-security/2013/09/06/2",
                "name": "[oss-security] 20130906 Re: CVE request: pyOpenSSL hostname check bypassing  vulnerability",
                "refsource": "MLIST",
                "tags": []
              },
              {
                "url": "https://mail.python.org/pipermail/pyopenssl-users/2013-September/000478.html",
                "name": "[pyOpenSSL-Users] 20130904 pyOpenSSL 0.13.1",
                "refsource": "MLIST",
                "tags": []
              },
              {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1005325",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1005325",
                "refsource": "CONFIRM",
                "tags": []
              },
              {
                "url": "http://www.ubuntu.com/usn/USN-1965-1",
                "name": "USN-1965-1",
                "refsource": "UBUNTU",
                "tags": [
                  "Vendor Advisory"
                ]
              },
              {
                "url": "http://www.debian.org/security/2013/dsa-2763",
                "name": "DSA-2763",
                "refsource": "DEBIAN",
                "tags": []
              },
              {
                "url": "http://lists.opensuse.org/opensuse-updates/2013-11/msg00015.html",
                "name": "openSUSE-SU-2013:1648",
                "refsource": "SUSE",
                "tags": []
              }
            ]
          },
          "description": {
            "description_data": [
              {
                "lang": "en",
                "value": "The X509Extension in pyOpenSSL before 0.13.1 does not properly handle a '\\0' character in a domain name in the Subject Alternative Name field of an X.509 certificate, which allows man-in-the-middle attackers to spoof arbitrary SSL servers via a crafted certificate issued by a legitimate Certification Authority."
              }
            ]
          }
        },
        "configurations": {
          "CVE_data_version": "4.0",
          "nodes": [
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.11:a1:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.10:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.9:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.8:a1:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:*:*:*:*:*:*:*:*",
                  "versionEndIncluding": "0.13",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.12:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.7:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.11:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:a:jean-paul_calderone:pyopenssl:0.11:a2:*:*:*:*:*:*",
                  "cpe_name": []
                }
              ]
            },
            {
              "operator": "OR",
              "children": [],
              "cpe_match": [
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:12.04:-:lts:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:13.04:*:*:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:10.04:-:lts:*:*:*:*:*",
                  "cpe_name": []
                },
                {
                  "vulnerable": true,
                  "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:12.10:*:*:*:*:*:*:*",
                  "cpe_name": []
                }
              ]
            }
          ]
        },
        "impact": {
          "baseMetricV2": {
            "cvssV2": {
              "version": "2.0",
              "vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "accessVector": "NETWORK",
              "accessComplexity": "MEDIUM",
              "authentication": "NONE",
              "confidentialityImpact": "NONE",
              "integrityImpact": "PARTIAL",
              "availabilityImpact": "NONE",
              "baseScore": 4.3
            },
            "severity": "MEDIUM",
            "exploitabilityScore": 8.6,
            "impactScore": 2.9,
            "obtainAllPrivilege": false,
            "obtainUserPrivilege": false,
            "obtainOtherPrivilege": false,
            "userInteractionRequired": false
          }
        },
        "publishedDate": "2013-09-30T21:55Z",
        "lastModifiedDate": "2013-12-08T06:00Z"
      }
    ]
  }
}